### ISSUE TITLE
Random ordering of facets

### ISSUE THREAD

**Issue by stuartlewis** [hectorcorrea/solr#1]
Hi!

Many thanks for publishing this code.  I've been using it for a library project to quickly make a faceted search user interface of a solr index made up of bibliographic data.

I've noticed that each time I refresh the page, the facets appear in a random order.  I presume this is due to golang not putting any order in maps? (https://nathanleclaire.com/blog/2014/04/27/a-surprising-feature-of-golang-that-colored-me-impressed/)

If so, do you know if there is an easy workaround for this, so that the facets always display in the same order?

(I'm not a proficient golang programmer!)

Many thanks,

Stuart

**Comment by stuartlewis** [comment]
Sorry - this is for the solrdora repository really

**Comment by atomotic** [comment]
i was dealing with the same behaviour, the code involved should be here:
https://github.com/hectorcorrea/solr/blob/master/searchResponse.go#L73
https://github.com/hectorcorrea/solr/blob/master/facets.go#L31

my current workaround is to have an additional function that ranges through the facets, checks the [title](https://github.com/hectorcorrea/solr/blob/master/facets.go#L14), and returns the array position.
is not very clever, i've not investigated if there are other ways to order a map

**Comment by hectorcorrea** [comment]
@stuartlewis sorry for the delayed reply, I didn't have notifications turned on for this repo and I didn't see your request from August! 

Yes, the random ordering must because of the way Go handles maps, but I should be able to  render them in the order in which they are indicated on the settings.json file. I'll take a look and get back to you (sooner than two months this time!)

**Comment by hectorcorrea** [comment]
@stuartlewis this was indeed tricky because I am using a `map[string]string` to read the Facets from the `settings.json file`, but an interesting one nonetheless.

I've posted a new version of [SolrDora](https://github.com/hectorcorrea/solrdora/tree/v0.3) that fixes this. You can now force the order of the facets by indicating it on the `setting.json` file:

```
...
"solrFacets": {
    "subjects_str": "1|Subjects",
    "publisher_str": "2|Publisher"
  },
...
```

**Comment by stuartlewis** [comment]
Hi @hectorcorrea 

Thank you for making these changes - that works brilliantly! I apprecite the time you spent on this.


Stuart
